-- =============================================================================
-- Staff Management Module — Database Migration  (v2 — case-preserved columns)
-- =============================================================================
-- Safe to run on the existing IMS Supabase project.
-- ALL new tables are prefixed with "staff_" to avoid any collision with the
-- existing tables (users, roles, permissions, products, sales, purchases, etc.)
--
-- IMPORTANT: Every camelCase identifier is double-quoted so Postgres stores
-- and returns it with its original case.  This matches the camelCase column
-- names used by every other IMS-owned table (users, sales, purchases, etc.)
-- and is required for Supabase JS client queries to work without column mapping.
--
-- Convention:
--   • camelCase column names, double-quoted in DDL
--   • UUID primary keys generated by gen_random_uuid()
--   • Soft-delete via "deletedAt" timestamp (NULL = active)
--   • "createdAt" / "updatedAt" both NOT NULL DEFAULT now()
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. staff  (core HR record)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable staff code, e.g. STF-001
  "staffCode"                 TEXT NOT NULL UNIQUE,

  -- Personal details
  "firstName"                 TEXT NOT NULL,
  "lastName"                  TEXT NOT NULL,
  email                       TEXT UNIQUE,
  phone                       TEXT,
  "photoUrl"                  TEXT,

  -- HR / employment
  -- "jobTitle" is a free-text HR label: "Store Manager", "Cashier", etc.
  -- It is intentionally NOT a FK to the system "roles" table.
  -- The "roles" table controls IMS login permissions; "jobTitle" is HR-only.
  "jobTitle"                  TEXT NOT NULL,
  branch                      TEXT,
  "employmentType"            TEXT NOT NULL DEFAULT 'Full-time',
  "joiningDate"               DATE,
  "baseSalary"                NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "isActive"                  BOOLEAN NOT NULL DEFAULT TRUE,

  // Optional link to the system users table (for staff who log into IMS).
  // NULL  = staff member has no IMS login account.
  // SET NULL on delete so removing a system user never wipes the HR record.
  "userId"                    UUID REFERENCES users(id) ON DELETE SET NULL,

  -- Supabase Auth UUID for the Staff PWA/Portal login account.
  -- Separate from userId — no FK constraint (soft reference to Supabase Auth).
  "portalUserId"              UUID,

  -- Today's attendance snapshot — updated whenever an attendance record is saved.
  -- Source of truth is staff_attendance; this field powers cheap directory queries.
  "currentAttendanceStatus"   TEXT NOT NULL DEFAULT 'Absent',

  "createdAt"                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  "deletedAt"                 TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_staff_userId    ON staff("userId")   WHERE "userId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_staff_isActive  ON staff("isActive");
CREATE INDEX IF NOT EXISTS idx_staff_deletedAt ON staff("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS idx_staff_jobTitle  ON staff("jobTitle");


-- ---------------------------------------------------------------------------
-- 2. staff_identity_documents  (national ID / passport / driving licence)
--    One row per staff member (1-to-1).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_identity_documents (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"               UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,

  "idType"                TEXT,
  "idNumber"              TEXT,
  "idExpiryDate"          DATE,

  -- Supabase Storage paths (returned as signed URLs by the app, never plain public URLs)
  "frontDocumentUrl"      TEXT,
  "backDocumentUrl"       TEXT,

  "verificationStatus"    TEXT NOT NULL DEFAULT 'Pending',
  "verifiedAt"            TIMESTAMPTZ,
  "verifiedByUserId"      UUID REFERENCES users(id) ON DELETE SET NULL,
  "rejectionReason"       TEXT,

  "createdAt"             TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_identity_staffId
  ON staff_identity_documents("staffId");


-- ---------------------------------------------------------------------------
-- 3. staff_emergency_contacts  (one per staff member)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_emergency_contacts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"       UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,

  "contactName"   TEXT NOT NULL,
  relationship    TEXT,
  phone           TEXT NOT NULL,

  "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_emergency_staffId
  ON staff_emergency_contacts("staffId");


-- ---------------------------------------------------------------------------
-- 4. staff_attendance  (one row per staff per date)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_attendance (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"           UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,

  "attendanceDate"    DATE NOT NULL,
  status              TEXT NOT NULL,
  "checkInTime"       TIME,
  "checkOutTime"      TIME,
  notes               TEXT,

  "recordedByUserId"  UUID REFERENCES users(id) ON DELETE SET NULL,
  "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_attendance_staff_date
  ON staff_attendance("staffId", "attendanceDate");

CREATE INDEX IF NOT EXISTS idx_staff_attendance_date    ON staff_attendance("attendanceDate");
CREATE INDEX IF NOT EXISTS idx_staff_attendance_staffId ON staff_attendance("staffId");


-- ---------------------------------------------------------------------------
-- 5. staff_tasks
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_tasks (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"           UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,

  title               TEXT NOT NULL,
  description         TEXT,
  priority            TEXT NOT NULL DEFAULT 'Medium',
  status              TEXT NOT NULL DEFAULT 'pending',
  "dueDate"           DATE,
  "completedAt"       TIMESTAMPTZ,

  "assignedByUserId"  UUID REFERENCES users(id) ON DELETE SET NULL,

  "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
  "deletedAt"         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_staff_tasks_staffId  ON staff_tasks("staffId");
CREATE INDEX IF NOT EXISTS idx_staff_tasks_status   ON staff_tasks(status);
CREATE INDEX IF NOT EXISTS idx_staff_tasks_dueDate  ON staff_tasks("dueDate");


-- ---------------------------------------------------------------------------
-- 6. staff_purchases
--    "productId" is TEXT to match products.id (TEXT in the shared storefront schema)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_purchases (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"               UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,

  "itemName"              TEXT NOT NULL,
  category                TEXT,

  -- Optional link to shared products catalog — TEXT to match products.id type
  "productId"             TEXT REFERENCES products(id) ON DELETE SET NULL,

  "purchaseDate"          DATE NOT NULL DEFAULT CURRENT_DATE,
  amount                  NUMERIC(12, 2) NOT NULL,

  "deductionStatus"       TEXT NOT NULL DEFAULT 'Pending',
  "deductedInPayslipId"   UUID,

  "recordedByUserId"      UUID REFERENCES users(id) ON DELETE SET NULL,

  "createdAt"             TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"             TIMESTAMPTZ NOT NULL DEFAULT now(),
  "deletedAt"             TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_staff_purchases_staffId         ON staff_purchases("staffId");
CREATE INDEX IF NOT EXISTS idx_staff_purchases_purchaseDate    ON staff_purchases("purchaseDate");
CREATE INDEX IF NOT EXISTS idx_staff_purchases_deductionStatus ON staff_purchases("deductionStatus");


-- ---------------------------------------------------------------------------
-- 7. staff_salary_records  (one row per staff per month)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_salary_records (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"             UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,

  "salaryMonth"         SMALLINT NOT NULL,
  "salaryYear"          SMALLINT NOT NULL,

  "baseSalary"          NUMERIC(12, 2) NOT NULL,
  "bonusAmount"         NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "purchaseDeductions"  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "otherDeductions"     NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "netPayable"          NUMERIC(12, 2) GENERATED ALWAYS AS
                          ("baseSalary" + "bonusAmount" - "purchaseDeductions" - "otherDeductions")
                        STORED,

  status                TEXT NOT NULL DEFAULT 'draft',
  "paidAt"              TIMESTAMPTZ,
  "approvedByUserId"    UUID REFERENCES users(id) ON DELETE SET NULL,
  notes                 TEXT,

  "createdAt"           TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_salary_staff_period
  ON staff_salary_records("staffId", "salaryYear", "salaryMonth");

CREATE INDEX IF NOT EXISTS idx_staff_salary_staffId ON staff_salary_records("staffId");


-- ---------------------------------------------------------------------------
-- 8. staff_payslips
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_payslips (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "staffId"             UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  "salaryRecordId"      UUID NOT NULL REFERENCES staff_salary_records(id) ON DELETE CASCADE,

  "payslipNumber"       TEXT NOT NULL UNIQUE,
  "generatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
  "documentUrl"         TEXT,
  "generatedByUserId"   UUID REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_staff_payslips_staffId        ON staff_payslips("staffId");
CREATE INDEX IF NOT EXISTS idx_staff_payslips_salaryRecordId ON staff_payslips("salaryRecordId");


-- ---------------------------------------------------------------------------
-- 9. Back-fill the deductedInPayslipId FK on staff_purchases
-- ---------------------------------------------------------------------------
ALTER TABLE staff_purchases
  ADD CONSTRAINT fk_staff_purchases_payslip
  FOREIGN KEY ("deductedInPayslipId")
  REFERENCES staff_payslips(id)
  ON DELETE SET NULL;


-- ---------------------------------------------------------------------------
-- 10. Add 'staff' resource permission rows for existing roles
--     Uncomment and adjust after confirming role IDs in your database.
-- ---------------------------------------------------------------------------
-- INSERT INTO permissions (id, "roleId", resource, "canCreate", "canRead", "canUpdate", "canDelete")
-- SELECT
--   gen_random_uuid(),
--   r.id,
--   'staff',
--   CASE r.name WHEN 'admin' THEN true WHEN 'manager' THEN true ELSE false END,
--   true,
--   CASE r.name WHEN 'admin' THEN true WHEN 'manager' THEN true ELSE false END,
--   CASE r.name WHEN 'admin' THEN true ELSE false END
-- FROM roles r
-- WHERE r."deletedAt" IS NULL
-- ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 11. Payment method tracking on staff_purchases  (v2 enhancement)
-- ---------------------------------------------------------------------------
-- Safe to run on existing data — both columns are nullable / have defaults.

ALTER TABLE staff_purchases
  ADD COLUMN IF NOT EXISTS "paymentMethod"  TEXT NOT NULL DEFAULT 'Salary Deduction',
  ADD COLUMN IF NOT EXISTS "paymentNote"    TEXT;

-- Update deductionStatus for any legacy rows that might be missing the value
-- (no-op if all rows already have a status)
UPDATE staff_purchases
  SET "deductionStatus" = 'Pending'
  WHERE "deductionStatus" IS NULL;

CREATE INDEX IF NOT EXISTS idx_staff_purchases_paymentMethod
  ON staff_purchases("paymentMethod");

-- ---------------------------------------------------------------------------
-- 12. Add portalUserId to staff table  (v3 enhancement)
--     Stores the Supabase Auth UUID for the staff member's PWA/Portal account.
--     Separate from userId (which is the POS's own local bcrypt users table FK).
--     No FK constraint — this is a soft reference to Supabase Auth, not a DB FK.
-- ---------------------------------------------------------------------------
ALTER TABLE staff
  ADD COLUMN IF NOT EXISTS "portalUserId" UUID;

CREATE INDEX IF NOT EXISTS idx_staff_portalUserId
  ON staff("portalUserId") WHERE "portalUserId" IS NOT NULL;

-- Fix Bishal Pandey and Binod Sthapa: clear any incorrect userId that was set
-- to a Supabase Auth UUID (wrong FK target). portalUserId will be set correctly
-- when the admin re-saves their credentials from the Edit Profile screen.
-- Uncomment and run ONLY if you see FK violations on staff.userId:
-- UPDATE staff SET "userId" = NULL WHERE "userId" IS NOT NULL
--   AND "userId" NOT IN (SELECT id FROM users);
