/**
 * gen_relink_sql.js
 * Generates a single SQL file that fixes everything in one transaction.
 * Run: node scripts/gen_relink_sql.js
 */
require('dotenv').config();
const XLSX = require('xlsx');
const fs   = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

// Load master
const wb   = XLSX.readFile(path.join(ROOT, 'Product_Master.xlsx'));
const ws   = wb.Sheets[wb.SheetNames[0]];
const rows = XLSX.utils.sheet_to_json(ws, { defval: '' });
const master = new Map();
for (const r of rows) {
  const code = parseFloat(r['Item Code']);
  if (!isNaN(code)) master.set(String(code), r);
}
console.log('Master rows:', master.size);

// Load CSV
const csv  = fs.readFileSync(path.join(ROOT, 'Supabase-producttable.csv'), 'utf8').trim().split('\n');
const hdrs = csv[0].split(',');
const ci   = n => hdrs.indexOf(n);
const IDX  = { id: ci('id'), sku: ci('sku') };

function parseLine(line) {
  const res = []; let cur = '', inQ = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') { if (inQ && line[i+1] === '"') { cur += '"'; i++; } else inQ = !inQ; }
    else if (ch === ',' && !inQ) { res.push(cur); cur = ''; }
    else cur += ch;
  }
  res.push(cur); return res;
}

const sq = v => v === null ? 'NULL' : "'" + String(v).replace(/'/g, "''") + "'";

// Group CSV rows by item code
const groups = new Map(); // codeStr -> [variantId, ...]
for (let i = 1; i < csv.length; i++) {
  if (!csv[i].trim()) continue;
  const cols = parseLine(csv[i]);
  const id   = cols[IDX.id]  || '';
  const sku  = cols[IDX.sku] || '';
  if (!id) continue;
  const code = parseFloat(sku.replace(/-\d+$/, ''));
  const cs   = isNaN(code) ? null : String(code);
  if (cs && master.has(cs)) {
    if (!groups.has(cs)) groups.set(cs, []);
    groups.get(cs).push(id);
  }
}
console.log('Matched groups:', groups.size);

// Build SQL
const lines = [];
lines.push('-- Single-transaction relink: generated by gen_relink_sql.js');
lines.push('-- Runs in seconds in Supabase SQL Editor');
lines.push('BEGIN;');
lines.push('');

// A. Upsert correct parent rows
lines.push('-- A. Upsert 2475 correct parents into product_variant_flat');
const flatVals = [];
for (const [cs, varIds] of groups) {
  const m     = master.get(cs);
  if (!m) continue;
  const name  = String(m['Item Name']   || '').trim();
  const cat   = String(m['Main Group']  || '').trim();
  const brand = String(m['Sub Group A'] || '').trim() || null;
  const base  = String(m['Base Unit']   || '').trim() || null;
  const pur   = parseFloat(m['P-Rate'])        || 0;
  const sell  = parseFloat(m['Selling Rate'])  || 0;
  const whole = parseFloat(m['W-SRate'])       || null;
  const tax   = m['VAT'] === 'Non-Taxable'     ? 0 : 13;
  const parentId = varIds[0]; // stable: first variant's UUID becomes parent id

  flatVals.push(
    '  (' + [sq(parentId), sq(name), sq(cs), sq(cat), sq(brand), sq(base),
             pur, sell, whole === null ? 'NULL' : whole, tax, sq('Active')
    ].join(',') + ')'
  );
}

lines.push('INSERT INTO product_variant_flat');
lines.push('  (id,name,slug,category,brand,base_unit,purchase_price,selling_price,wholesale_price,tax_rate,status)');
lines.push('VALUES');
lines.push(flatVals.join(',\n'));
lines.push('ON CONFLICT (id) DO UPDATE SET');
lines.push("  name=EXCLUDED.name,slug=EXCLUDED.slug,category=EXCLUDED.category,brand=EXCLUDED.brand,");
lines.push("  base_unit=EXCLUDED.base_unit,purchase_price=EXCLUDED.purchase_price,");
lines.push("  selling_price=EXCLUDED.selling_price,wholesale_price=EXCLUDED.wholesale_price,");
lines.push("  tax_rate=EXCLUDED.tax_rate,status='Active';");
lines.push('');

// B. Re-link variants — one UPDATE per parent group
lines.push('-- B. Re-link all 14818 variants to correct parent');
for (const [cs, varIds] of groups) {
  const parentId = varIds[0];
  const idList   = varIds.map(id => "'" + id + "'").join(',');
  lines.push('UPDATE product_variant SET product_flat_id=' + sq(parentId) + ' WHERE id IN (' + idList + ');');
}
lines.push('');

// C. Delete flat rows that now have no variants (the old duplicates)
lines.push('-- C. Delete orphaned flat rows (old 1:1 rows replaced by correct parents)');
lines.push('DELETE FROM product_variant_flat pvf');
lines.push("WHERE status <> 'Archived'");
lines.push('  AND NOT EXISTS (SELECT 1 FROM product_variant pv WHERE pv.product_flat_id = pvf.id);');
lines.push('');

// D. Summary
lines.push('-- D. Summary check');
lines.push("SELECT 'product_variant_flat' AS tbl, COUNT(*) FROM product_variant_flat");
lines.push('UNION ALL');
lines.push("SELECT 'product_variant', COUNT(*) FROM product_variant");
lines.push('UNION ALL');
lines.push("SELECT 'orphan_variants', COUNT(*) FROM product_variant");
lines.push('  WHERE product_flat_id NOT IN (SELECT id FROM product_variant_flat);');
lines.push('');
lines.push('COMMIT;');

const sql = lines.join('\n');
const outPath = path.join(ROOT, 'supabase', 'relink_final.sql');
fs.writeFileSync(outPath, sql, 'utf8');
const sizeKB = Math.round(Buffer.byteLength(sql) / 1024);
console.log('Written:', outPath);
console.log('Size:', sizeKB + 'KB, Lines:', lines.length);
